name: 🏓 backend-cd

# on:
#   push:
#     branches:
#       - main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CONTAINER_NAME: arunavabasu03/radisapp_backend
  PROJECT_ID: ${{ secrets.CLOUD_RUN_PROJECT_NAME }}
  REGION: us-east1

  REPO_NAME: nextjs-cloud-run

jobs:
  backend-test:
    name: 🧪 backend-ci
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"
      - name: Install dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests and coverage
        run: |
          cd backend
          pytest
          coverage run --source=src -m pytest -v __tests__/ && coverage report -m && coverage html && coverage xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          flags: backend
          files: ./backend/coverage.xml

  backend-deploy:
    name: 🚀 Deploy to production
    needs: backend-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && success()
    runs-on: ubuntu-latest
    steps:
      # checkout github repo
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: arunavabasu03
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT }}"

      - name: Build and push Docker image
        run: |
          docker build -t $CONTAINER_NAME:${{ github.sha }} -t $CONTAINER_NAME:latest .

          docker push $CONTAINER_NAME:${{ github.sha }}

          docker push $CONTAINER_NAME:latest

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"

      - name: Deploy to Cloud Run
        run: |
           gcloud run deploy $REPO_NAME \
           --region $REGION \
           --image  $CONTAINER_NAME:latest\
           --platform "managed" \
           --quiet
