name: Preview deployment

on:
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  CI:
    runs-on: ubuntu-latest
    env:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          role-session-name: RadisAppPreviewDeploySession
          aws-region: us-east-2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"

      - name: Install Node.js dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Deploy to AWS
        run: yarn cdk deploy --ci --require-approval never RadisAppStackPreview
